name: Render and Deploy RMarkdown Website

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      #- uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            any::knitr
            any::yaml
            any::prettydoc
            any::devtools
            github::hadley/emo

      # - name: Install dependencies
      #   run: |
      #     install.packages(c("rmarkdown", "knitr", "yaml"))
      #   shell: Rscript {0}

      - name: Render site
        run: Rscript -e 'rmarkdown::render_site()'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
